In [26]:
import matplotlib.pyplot as plt
import numpy as np


%matplotlib widget
plt.ioff()

def plot_sets(ax,gr=False,ti='',xla=False,yla=False,zla=False,xli=False,yli=False,zli=False,ticks_off=False,xticks_off=False,yticks_off=False,zticks_off=False, ba=False, ar=False,leg=False,view=False):
    
    ax.set_title(ti)
    if gr:  ax.grid(gr);ax.set_axisbelow(True)
    if xla: ax.set_xlabel(xla)
    if yla: ax.set_ylabel(yla)
    if zla: ax.set_zlabel(zla)

    if xticks_off: ax.set_xticklabels([])
    if yticks_off: ax.set_yticklabels([])
    if zticks_off: ax.set_zticklabels([])

    if   ticks_off==1: ax.set_xticklabels([]); ax.set_xticks([]);ax.set_yticklabels([]); ax.set_yticks([])
    elif ticks_off==2: ax.set_xticklabels([]); ax.set_xticks([])
    elif ticks_off==2: ax.set_yticklabels([]); ax.set_yticks([])

    if ba: ax.set_box_aspect(ba)
    if ar: ax.set_aspect(ar)

    if xli: ax.set_xlim(xli)
    if yli: ax.set_ylim(yli)
    if zli: ax.set_zlim(zli)

    if leg: ax.legend(**leg)

    if view:ax.view_init(**view)

SMALL_SIZE  = 8
MEDIUM_SIZE = 10

# title
plt.rc('axes',titlesize=MEDIUM_SIZE,titleweight='bold')
# xy-labells
plt.rc('axes',labelsize=SMALL_SIZE)
# xy-ticks
plt.rc('xtick',labelsize=SMALL_SIZE)
plt.rc('ytick',labelsize=SMALL_SIZE)
    
px2inch = 1/plt.rcParams['figure.dpi']

In [30]:
def rand_mats(D,N):
    X = np.random.rand(D,N)
    W = np.random.randn(D,D)
    B = np.random.randn(D,1)
    return W,B,X

def linear_trans(X,W,B):
    return W@X + B

def soft_max_cols(mat):
    D,_     = mat.shape
    mat     = mat/np.sqrt(D)
    mat_exp = np.exp(mat)
    return mat_exp/np.sum(mat_exp,axis=0)


D = 4   # Embedding length
N = 3   # No words
#############################

_,_,X   = rand_mats(D,N)
Wq,Bq,_ = rand_mats(D,N)
Wk,Bk,_ = rand_mats(D,N)
Wv,Bv,_ = rand_mats(D,N)

Q  = linear_trans(X,Wq,Bq)
K  = linear_trans(X,Wk,Bk)
V  = linear_trans(X,Wv,Bv)
A  = soft_max_cols(K.T@Q)
SA = V @ A

print('X' ,X,X.shape)
print('V' ,V,V.shape)
print('A' ,A,A.shape)
print('SA',SA,SA.shape)



X [[0.6198117  0.35291359 0.23397113]
 [0.77823638 0.13581714 0.24669742]
 [0.19372972 0.52184468 0.43077159]
 [0.79683575 0.86917759 0.26448975]] (4, 3)
V [[-1.91960226 -2.28558063 -1.73881039]
 [-0.30624808  0.16231124 -1.12144942]
 [ 1.79843141  0.63631607  1.03447964]
 [-0.50643762  0.01965505 -0.06954999]] (4, 3)
A [[0.47952566 0.56051781 0.43473246]
 [0.16341823 0.23731716 0.32525828]
 [0.35705611 0.20216503 0.24000926]] (3, 3)
SA [[-1.91485696 -1.96990542 -1.99524804]
 [-0.52074956 -0.35985611 -0.34950115]
 [ 1.33574693  1.36819717  1.23708827]
 [-0.26447109 -0.2932634  -0.23046454]] (4, 3)


In [241]:
def soft_max_cols(mat,scaling=True):

    D,_     = mat.shape
    if scaling: mat = mat/np.sqrt(D)

    mat_exp = np.exp(mat)
    return mat_exp/np.sum(mat_exp,axis=0)

mat0 = np.random.rand(3,4)*10
mat1 = soft_max_cols(mat0,scaling=False)
mat2 = soft_max_cols(mat0,scaling=True )

print(mat1)
print('')
print(mat2)


[[2.48583343e-01 2.31811560e-02 2.89564943e-04 1.34147623e-02]
 [7.51119424e-01 7.13111717e-02 9.99063233e-01 6.91201453e-02]
 [2.97233321e-04 9.05507672e-01 6.47202005e-04 9.17465092e-01]]

[[0.34316545 0.08919229 0.00885808 0.0664734 ]
 [0.64978324 0.17064251 0.9770489  0.17129069]
 [0.00705131 0.74016521 0.01409303 0.76223591]]
