In [3]:
import numpy as np

### Matrix indexing: Modulo Operator vs Floor Division

In [12]:
n = 3
X = np.zeros((n,n))
Y = np.zeros((n,n))

for i in range(n*n):
    row = i // n
    col = i %  n
    X[row,col] = col
    Y[row,col] = row

print(X);print(Y)

[[0. 1. 2.]
 [0. 1. 2.]
 [0. 1. 2.]]
[[0. 0. 0.]
 [1. 1. 1.]
 [2. 2. 2.]]


### Matrix fill using Zip

In [7]:

def fill_matrix_1(Ny,Nx):
    x   = np.linspace(0,100,Nx) # Ncols
    y   = np.linspace(0,100,Ny) # Nrows
    X,Y = np.meshgrid(x,y)
    C   = np.random.rand(Ny,Nx)
    M   = np.zeros_like(X)
    for row in range(Ny):
        for col in range(Nx):
            M[row,col] = x[col]*y[row]*C[row,col]

    return X,Y,M

def fill_matrix_2(Nx,Ny):
    x   = np.linspace(0,100,Nx) # Ncols
    y   = np.linspace(0,100,Ny) # Nrows
    X,Y = np.meshgrid(x,y)
    C   = np.random.rand(Ny,Nx)
    M   = []
    for x,y,c in zip(X.flatten(),Y.flatten(),C.flatten()):
            M.append(x*y*c)
    
    return X,Y,np.reshape(M,(Ny,Nx))

k   = 100
Nx  = 7*k
Ny  = 5*k

# %timeit fill_matrix_1(Nx,Ny)
# %timeit fill_matrix_2(Nx,Ny)


124 ms ± 2.55 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
176 ms ± 1.82 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
